<a href="https://colab.research.google.com/github/sathvik-ujwal/Lab-Codes/blob/main/MACHINE%20LEARNING/classification_metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.metrics import roc_curve, auc, precision_recall_curve
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification

In [30]:
X, y = make_classification(n_samples=30, n_features=2, n_redundant=0, random_state=42)

In [31]:
model = LogisticRegression()
model.fit(X, y)
y_pred = model.predict(X)
print(y_pred)

[0 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0]


In [32]:
print("confusion matrix")
cm = confusion_matrix(y, y_pred)
print(cm)

accuracy = accuracy_score(y, y_pred)
recall = recall_score(y, y_pred)
precision = precision_score(y, y_pred)
f1 = f1_score(y, y_pred)

print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 Score:", f1)

confusion matrix
[[14  1]
 [ 0 15]]
Accuracy: 0.9666666666666667
Recall: 1.0
Precision: 0.9375
F1 Score: 0.967741935483871


In [33]:
confusion_matrix = np.zeros((2,2), dtype = int)
for true, pred in zip(y, y_pred):
  confusion_matrix[true][pred] += 1
print(confusion_matrix)


[[14  1]
 [ 0 15]]


In [34]:
TP = confusion_matrix[1][1]
TN = confusion_matrix[0][0]
FP = confusion_matrix[0][1]
FN = confusion_matrix[1][0]
print(TP, TN, FP, FN)

15 14 1 0


In [35]:
accuracy = (TP + TN)/ (TP + TN + FP + FN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)
f1_score = 2 * (precision * recall)/ (precision + recall)

print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 Score:", f1_score)

Accuracy: 0.9666666666666667
Recall: 1.0
Precision: 0.9375
F1 Score: 0.967741935483871
